### PR TITLE
Fix property resolvers environment variable name

### PR DESCRIPTION
**Pull request by debovema**
See https://github.com/TIBCOSoftware/flogo-lib/commit/e06ea66fe8367f19f033fff512dda7b14f628ba7 for details

### CODE REVIEW

**Comment by fm-tibco** [comment]
Hi @debovema, I don't see the property name change in this PR, just the previous fix for options.

**Comment by debovema** [comment]
Oops sorry. Pushed the wrong branch.

**Comment by vijaynalawade** [comment]
@debovema : I fixed the name in old repo based on name from the new repo.

**Comment by debovema** [comment]
@vijaynalawade : I know the old one is the correct one but there is a **S** missing however.
@fm-tibco : I rebased and force-pushed the right fix

**Pull request merged**
