### PR TITLE
Additional characters for function name and item name

### PR DESCRIPTION
**Pull request by lixingwang**
**What kind of change does this PR introduce?** (check one with "x")
```
[*] Bugfix
[] Feature
[] Code style update (formatting, local variables)
[] Refactoring (no functional changes, no api changes)
[] Other... Please describe:
```

**Fixes**: #

**What is the current behavior?**
The function name cannot have `_`, and the resolver item name cannot handle `.` , `-` and `_`
**What is the new behavior?**
1. Added `.`,  `_` and `-` for the item name. such as: `$property[Marketo.Connection.client_id]` or $property[Marketo.Connection.secret-key]`
2. Added `_` support for the function name

### CODE REVIEW

**Comment by fm-tibco** [comment]
I think this is confusing.  In our script "language" `.` is used to traverse an object and is not valid as a part of an identifier.  I think they shouldn't be allowed to be used directly in property lookup.  They should be escaped... so if you want to use periods, you have to put it in quotes.  ```$property["Marketo.Connection.client_id"]```.  @mellistibco thoughts?

**Comment by mellistibco** [comment]
I agree with @fm-tibco. I don't particularly think we should introduce `.` due to the double meaning. I'm ok with `_` and `-`, however.

**Comment by lixingwang** [comment]
@mellistibco Are you agree to add quotes if we introduce `.`? 

Why we need `.` the reason: We are introducing a property group and the `.` as the group separator,   taking an example of the Marketo one, Marketo is top level and connection second level and client id is a leaf node.

Marketo 
	Connection
		Client_id,

We used `.` as a delimiter, in that case, if we remove `.` we need another character to act as a delimiter.   _ and - cannot because it can be a level property name as well.

**Comment by vijaynalawade** [comment]
@fm-tibco @mellistibco : In 058, hierarchy was presented using dot. We have many apps with those. We also have many property resolver implementations that rely on dot to determine the hierarchy.  Let's see if can be supported.
CC: @rishikeshpalve

**Comment by fm-tibco** [comment]
Valid identifiers don't need double quotes, but if you are going to use `.` or `-` then we should use double quotes.

**Comment by mellistibco** [comment]
We'll need to support double quotes for anything with `.` or `-`. Properties are just labeled strings, not objects so we'll need to wrap in quotes/escape the label.

**Comment by lixingwang** [comment]
@fm-tibco @mellistibco  to be clear, we will remove quotes while resolving the value(GetResolution method), is that right?

**Comment by fm-tibco** [comment]
Yes, just in the script they require the quotes to kind of "escape" to those values

**Pull request merged**
