### PR TITLE
Feature code generation

### PR DESCRIPTION
**Pull request by pointlander**
**What kind of change does this PR introduce?** (check one with "x")
```
[] Bugfix
[x] Feature
[] Code style update (formatting, local variables)
[] Refactoring (no functional changes, no api changes)
[] Other... Please describe:
```

**Fixes**: #

**What is the current behavior?**
Flogo API code generation from Flogo definition is not supported.

**What is the new behavior?**
Adds Flogo API code generation from Flogo definition. Supports code generation extensions for Actions. Some Flogo API bugs are also fixed.

### CODE REVIEW

**Comment by skothari-tibco** [comment]
So the goal of this API is to create a Go file that uses Flogo API's to run flogo app, from any app descriptor json ?

**Comment by pointlander** [comment]
That is the idea. @skothari-tibco 

See this for an example application: https://github.com/pointlander/asyncapi-flogo/blob/master/transform/transform.go#L685

And this for the Microgateway Action specific code generator: https://github.com/project-flogo/microgateway/blob/feature-code-generation/action.go#L188

**Comment by skothari-tibco** [comment]
I have been testing this feature. I came across some issues. Is it assumed that before creating the Go file, all the contributions are imported ? Do we need this assumption ? Why do some contribution aliases start with "port" ?  

There are couple of bugs in the code for eg. I got `trg0 := app.NewTrigger(&#rest.Trigger{}, map[string]interface {}{"port":"3009"})` #rest.Trigger should be just rest.  
Also I have no idea what's happening here 
```
action0_0_0.SetOutputMappings([]string{"", "code==$.out"})
_ = action0_0_0
_ = handler0_0
_ = trg0
```

**Comment by pointlander** [comment]
> I have been testing this feature. I came across some issues. Is it assumed that before creating the Go file, all the contributions are imported ? Do we need this assumption ? Why do some contribution alias start with "port" ?

The Flogo API requires all Functions, Actions, Triggers, and Activities that are utilized in the application to be imported. When there is an import conflict, the import is aliased with a name port<unique number>.

I will implement an automated test of the generator.

**Comment by pointlander** [comment]
I am not sure how you are getting: '#rest.Trigger'? @skothari-tibco

**Comment by skothari-tibco** [comment]
I'm using this two files for testing. I made sure that I'm using your fork. I'm getting the following error .
`panic: error unmarshalling flow: activity '#log' not imported` at line #115 .
Am I missing something ?

[temp.txt](https://github.com/project-flogo/core/files/3197890/temp.txt)
[flogo.txt](https://github.com/project-flogo/core/files/3197891/flogo.txt)

**Comment by pointlander** [comment]
`#log` issue has been fixed @skothari-tibco

**Comment by skothari-tibco** [comment]
Shouldn't we also add `app.AddResource("flow:simple_flow", json.RawMessage(flogoJSON))` this to load the flow resource ?

**Comment by pointlander** [comment]
@skothari-tibco That should be added in a 'Generate' function in the Flow Action. Other modifications to the Flow Action are needed. Currently, only the Micorgateway Action supports 'Generate': https://github.com/project-flogo/microgateway/blob/feature-code-generation/action.go#L188

**Comment by fm-tibco** [comment]
For actions that don't have a "generate", can't we just configure the action with the provided settings? and just register the resources?  Does it need a custom generator if it isn't doing anything special?

**Comment by pointlander** [comment]
Actions reference resources in different ways. Only the Action knows how to get to the Resource.

**Comment by fm-tibco** [comment]
True.  I'm just saying to register the resource, the configured action will pick up the resource on its own. That's how you can use the flow action now in the api. example:

```
app.AddResource("flow:test", flowJson)
h.NewAction(&flow.FlowAction{}, flow.Settings{FlowURI:"res://flow:test"})
```

**Comment by pointlander** [comment]
This will create a problem for the Microgateway. It needs to know not to register the resource for the Microgateway.

**Comment by fm-tibco** [comment]
Maybe the "generate" interface can indicate wither to register its resources or not?  Or something along those lines?  So that way all actions that don't have the generate can work by default.

**Comment by pointlander** [comment]
It is currently not known which Resource types are associated with which Actions. An interface/function could be added to the Resource Manager: https://github.com/project-flogo/microgateway/blob/feature-code-generation/action.go#L52
so that the generator knows not to load/add Microgateway resources.

**Comment by pointlander** [comment]
Resources are now added by default. @fm-tibco

**Comment by mellistibco** [comment]
out of curiosity, what is the reason to generate the code from the json?

**Comment by pointlander** [comment]
It is for this project: https://github.com/pointlander/asyncapi-flogo
which converts AsyncAPI into a Flogo Application (JSON or Go) @mellistibco

**Comment by fm-tibco** [comment]
@skothari-tibco can you re-run your tests and add review this PR.

**Comment by skothari-tibco** [comment]
@fm-tibco Sure.

**Comment by skothari-tibco** [comment]
Should this be a part of core, cli or a cli plugin ? I don't see this being a proper addition to the core api I believe that the core API should be used to work with components of core like engine, action, trigger etc. and not JSON files. I see this as a part of CLI as we wanna convert from JSON to Go app instead of Flogo App. 

@fm-tibco @mellistibco @pointlander thoughts ?

**Comment by pointlander** [comment]
My only requirement is that I need to be able to import the generator into other projects that require go Flogo API code generation. The code generator also needs to generate code that is consistent with the Flogo API. If the Flogo API changes, the code generator will need to be updated.

**Comment by pointlander** [comment]
Generation code has been moved into microgateway. Bug fixes are in a new pull request: https://github.com/project-flogo/core/pull/111

**Pull request closed without merging**
