### PR TITLE
fix support for external property resolution

### PR DESCRIPTION
**Pull request by fm-tibco**
Port of:

https://github.com/TIBCOSoftware/flogo-lib/pull/262
https://github.com/TIBCOSoftware/flogo-lib/pull/266

### CODE REVIEW

**Comment by mellistibco** [comment]
@debovema can you also take a look?

**Comment by debovema** [comment]
Great that it has been ported. I will take a look with a real-world use case directly on this "branch" to validate everything.
It looks good to me as far as I can see so you can merge this version without waiting for me.

**Comment by debovema** [comment]
I found a little issue.

If I don't add ```_ "github.com/project-flogo/core/app/propertyresolver"``` in *imports.go* file, the package is not imported and the init() functions of "built-in resolvers" are not even called and these resolvers are not available. Even though I set ```FLOGO_APP_PROPS_JSON``` for instance.

The fix is easy but how do you plan to enable the resolvers for the end-users ?
Should the import be included by default in *imports.go* ? Should it be elsewhere ? Should it be added manually or "on-demand" (by the CLI?) in *imports.go* ?

**Comment by fm-tibco** [comment]
We could choose to have both env & json as available by default (they are pretty small).  @mellistibco @vijaynalawade ?

As for a user specified one, that will have to go in the imports.go.  For now it will have to be manually, we could add support to install it via the CLI as well.  It's not something that is don't very frequently, so I'm not opposed to keeping it as a manual step.

**Comment by debovema** [comment]
I agree that they are certainly very small.
However maybe in some cases (IoT) it could be useful to disable them. With this option, the best choice would be to add the import in the default project template of the CLI. A short comment on the same line could even explain *why* there is this import.

**Comment by fm-tibco** [comment]
I'm going to merge this in and create a PR for the initialization of the property resolvers

**Pull request merged**
