### PR TITLE
conditional mapping

### PR DESCRIPTION
**Pull request by lixingwang**
**What kind of change does this PR introduce?** (check one with "x")
```
[] Bugfix
[*] Feature
[] Code style update (formatting, local variables)
[] Refactoring (no functional changes, no api changes)
[] Other... Please describe:
```

**Fixes**: #204 

**What is the current behavior?**
Today we have ternary expression but ternary expression cannot work with object or array. and ternary expression also difficult to maintain if the condition is complex. 

So we come up with if/else condition mapping. the proposal we list in #204 
**What is the new behavior?**
We able to do if/else conditional mapping that user can map value base on different condition
Example:

* Single field/Primitive type
```
{
  "myInput": {
    "@if($.pathParams.myParam == \"abc\")": "This is param for abc",
    "@elseif($.pathParams.myParam == \"foo\")": "This is param for foo",
    "@elseif($.pathParams.myParam == \"xxxx\")": "This is param for xxx",
    "@else": "This is param for else"        
  }
}
```
* Work with object mapper
```
{
  "bookDetail": {
    "mapping": {
      "id": "=$.book.id",
      "name": "=$.book.id",
      "address": "=$.book.address",
      "category": {
        "@if($.book.price >= 100)": "High",
        "@elseif($.book.price >= 50 && $.book.price < 100)": "Medium",
        "@else": "Low"
      }
    }
  }
}
```

* Work with array mapping
```
{
  "store": {
    "mapping": {
      "@if($.store.name == \"Walmart\")": {
        "@foreach($.store.books, \"book\")": {
          "id": "=$loop.city",
          "name": "=$loop.state",
          "address": "=$.store.address",
          "category": {
            "@if($.book.price >= 100)": "High",
            "@elseif($.book.price >= 50 && $.book.price < 100)": "Medium",
            "@else": "Low"
          }
        }
      },
      "@elseif($.store.name == \"Target\")": {
        "@foreach($.store.books, \"book\")": {
          "id": "=$loop.city",
          "name": "=$loop.state",
          "address": "=$.store.address",
          "category": {
            "@if($.book.price >= 100)": "Good",
            "@elseif($.book.price >= 50 && $.book.price < 100)": "Average",
            "@else": "Poor"
          }
        }
      },
      "@else": {
        "@foreach($.store.books, \"book\")": {
          "id": "=$loop.city",
          "name": "=$loop.state",
          "address": "=$.store.address"
        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by fm-tibco** [comment]
Are you proposing adding this outside of the of object mapping?  Basically an expression of sorts? 

I'm not sure about this:
```
{
  "myInput": {
    "@if($.pathParams.myParam == \"abc\")": "This is param for abc",
    "@elseif($.pathParams.myParam == \"foo\")": "This is param for foo",
    "@elseif($.pathParams.myParam == \"xxxx\")": "This is param for xxx",
    "@else($.pathParams.myParam == \"else\")": "This is param for else"        
  }
}
```

This is not an expression and goes outside of the norm of any expressions I know.  We have more flexibility in object/array mapping because it is a little closer to scripting and basically a collection of expressions.  We got away from this inferred mapping type syntax.

Maybe consider doing an custom function... maybe something like:
```
"= utils.case($.pathParams.myParam, "abc", "abc result", "foo", "foo result", "#default", "the else")"
```

**Comment by lixingwang** [comment]
> Are you proposing adding this outside of the of object mapping? Basically an expression of sorts?
> 
> I'm not sure about this:
> 
> ```
> {
>   "myInput": {
>     "@if($.pathParams.myParam == \"abc\")": "This is param for abc",
>     "@elseif($.pathParams.myParam == \"foo\")": "This is param for foo",
>     "@elseif($.pathParams.myParam == \"xxxx\")": "This is param for xxx",
>     "@else($.pathParams.myParam == \"else\")": "This is param for else"        
>   }
> }
> ```
> 
> This is not an expression and goes outside of the norm of any expressions I know. We have more flexibility in object/array mapping because it is a little closer to scripting and basically a collection of expressions. We got away from this inferred mapping type syntax.
> 
> Maybe consider doing an custom function... maybe something like:
> 
> ```
> = utils.case($.pathParams.myParam, "abc", "abc result", "foo", "foo result", "#default", "the else")
> ```

I would avoid calling it expression, I like to call it mapper.  As of today, we have strict mapper, object mapper, and if/else mapper. 
* Strict mapper it's a single expression
* Object mapper is a collection of expressions work on the complex data type
* `if/else` is collection of object mapper and strict mapper base on condition. 

`If/else` is another mapper so it should work with any field,  it also easier to use for UI or developer,  comparing with a static function or ternary expression we have today

I don't like function because if/else case makes function hard to use and read, there might be too many arguments and complex/long conditions.  The example you shared is a switch case but we are talking about `if/else`.  A little different.

I like `if/else` because it is applicable for all fields no matter it is a top field with primitive type or leaf field on the complex type, as long as the user knows if/else formula they should be good to go.  There is no reason that if/else works with a leaf node but not work with a single field(top field).

**Comment by fm-tibco** [comment]
What is the use case for this?  Is this typically used for only one input.. or are they going to be used to "flavor" an activity.

for example:
```
{
  "myInput1": {
    "@if($.pathParams.myParam == \"dev\")": "This is param for abc",
    "@elseif($.pathParams.myParam == \"test\")": "This is param for foo",
    "@elseif($.pathParams.myParam == \"prod\")": "This is param for xxx",
    "@else": "This is param for else"        
  },
  "myInput2": {
    "@if($.pathParams.myParam == \"dev\")": "This is param for abc",
    "@elseif($.pathParams.myParam == \"test\")": "This is param for foo",
    "@elseif($.pathParams.myParam == \"prod\")": "This is param for xxx",
    "@else": "This is param for else"        
  }
}
```

Also shouldn't 
```
    "@else($.pathParams.myParam == \"else\")": "This is param for else" 
```
just be:
```
    "@else": "This is param for else" 
```

**Comment by lixingwang** [comment]
@fm-tibco Right. Only `@if` and `@elseif' have the condition, `@else` doesn't have the condition. (edited description) so it should just
```
 "@else": "This is param for else"
```

`if/else` designs for single field only, it cannot work across fields, but 2 dependent fields can have their own `if/else`, so the example you have `myInput1 `and `myInput2` is a valid case.

Why:
1. User can do if/else on the root attribute field as well, today only way is the ternary expression which is not good., mentioned above
2. Keep consistent with all fields no matter it is child or root or primitive or object field, we support `if/else` for all fields type. We can say that `if/else` just map framework it doesn't care about field type.

Use case:
Customers have a use case where they want to send data to different CRM target systems using rest invoke where they want to change URL base on data.

I think it is really useful in real app design.

**Comment by lixingwang** [comment]
@mellistibco @fm-tibco Any progress?

**Comment by fm-tibco** [comment]
How about something like:
```
"myInput": {
	"@switch($.pathParams.myParam)" :
	{
		"abc":"This is param for abc",
		"foo":"This is param for foo",
		"@default":"This is param for else" 
	}
}
```

**Comment by lixingwang** [comment]
@fm-tibco  The question more like what is the difference between `if/else` and `switch`.  We can add `switch` supports as well If you want. but today we focusing on if/else because we want base on conditions with operator `||``&&``<, >=, <, <=, ==` etc. I think that cannot be done with switch.

**Comment by fm-tibco** [comment]
You had mentioned that readability is a concern.. and the current if/else is a little hard to read... hence why I suggested something like the switch.

**Comment by fm-tibco** [comment]
Just trying to simplify the structure so its not completely like scripting, maybe even something like:

```

"myInput": {
	"@if($.pathParams.myParam)" :
	{
		">abc":"This is param for abc",
		"<foo":"This is param for foo",
		"@else":"This is param for else" 
	}
}
```

**Comment by lixingwang** [comment]
@fm-tibco em... `if`, `elseif` `else` mostly on the same node level.  now it moves as child node of @if.   

Question:  How we handle nested @if  if we go with this structure?  such as the example(**Work with array mapping**) in the description?

**Comment by fm-tibco** [comment]
Btw, my suggestions are just some possible alternatives to the syntax. I think the main thing I'm pointing out is that we use "mapping" to denote that we are doing something special, hence why I chose to follow something similar to you a mapping is defined

This could be possiblity:

```
{
  "store": {
    "@if": {
      "$.store.name == \"Walmart\"": {
        "@foreach($.store.books, \"book\")": {
          "id": "=$loop.city",
          "name": "=$loop.state",
          "address": "=$.store.address",
          "category": {
            "@if($.book.price >= 100)": "High",
            "@elseif($.book.price >= 50 && $.book.price < 100)": "Medium",
            "@else": "Low"
          }
        }
      },
      "$.store.name == \"Target\"": {
        "@foreach($.store.books, \"book\")": {
          "id": "=$loop.city",
          "name": "=$loop.state",
          "address": "=$.store.address",
          "category": {
            "@if($.book.price >= 100)": "Good",
            "@elseif($.book.price >= 50 && $.book.price < 100)": "Average",
            "@else": "Poor"
          }
        }
      },
      "@else": {
        "@foreach($.store.books, \"book\")": {
          "id": "=$loop.city",
          "name": "=$loop.state",
          "address": "=$.store.address"
        }
      }
    }
  }
}


{
  "bookDetail": {
    "mapping": {
      "id": "=$.book.id",
      "name": "=$.book.id",
      "address": "=$.book.address",
      "category": { 
        "@if": 
        {
          "$.book.price >= 100": "High",
          "$.book.price >= 50 && $.book.price < 100)": "Medium",
          "@else": "Low"
        }
      }
    }
  }
}
```

**Comment by lixingwang** [comment]
@fm-tibco ok, I am fine with this structure.   @mellistibco @vijaynalawade  any thoutghts?

**Comment by lixingwang** [comment]
We had a call to discuss this.  and we come up with below possible solutions

We need to maintain the order of `elseif` so we came up with the below proposals.

1. Changed `elseif` to the array to have the ordered.
```
{
  "myInput": {
    "@if($.pathParams.myParam == \"abc\")": "This is param for abc",
    "@elseif": [
      {
        "$.pathParams.myParam<foo": "This is param for foo"
      }
    ],
    "@else": "This is param for else"
  }
}
```

2. Having @fm-tibco's proposal to change to the array to maintain order. first one would be if condition then elseif
```
"myInput": {
  "@if" :[
    {
      "$.pathParams.myParam<foo":"This is param for foo"
    }，
    {
      "$.pathParams.myParam<foo":"This is param for foo"
    }，
    {
      "@else":"This is param for foo"
    }
  ]
}
```
3. We can add a switch case as well
```
"myInput": {
  "@switch($.pathParams.myParam)" :
  {
    "abc":"This is param for abc",
    "foo":"This is param for foo",
    "@default":"This is param for else" 
  }
}
```

4.  We also found another alternative way which something like condition table which can handle if/else and switch
```
"myInput": {
  "@Conditions" :[
    {
      "$.pathParams.myParam<foo":"This is param for foo"
    }，
    {
      "$.pathParams.myParam>foo":"This is param for foo"
    }，
    {
      "$.pathParams.myParam == 200":"200"
    }，
    {
      "@otherwise": "otherwise"
    }
  ]
}
```

@mellistibco @fm-tibco @vijaynalawade:  Let's thinking more and get final conclusion as soon as possible

**Comment by fm-tibco** [comment]
How about "@condition/@conditional" which has a verbose generalized syntax, but also support an optional shorthand when using the same variable?

general:
```
  "myInput": {
  "@conditional" :[
    {
      "$.pathParams.myParam1<foo":"This is param for foo"
    }，
    {
      "$.pathParams.myParam2>foo":"This is param for foo"
    }，
    {
      "$.pathParams.myParam == 200":"200"
    }，
    {
      "@otherwise": "otherwise"
    }
  ]
```

shorthand:
```
"myInput": {
  "@conditional($.pathParams.myParam)" :[
    {
      "<foo":"This is param for foo"
    }，
    {
      ">foo":"This is param for foo"
    }，
    {
      "==200":"200"
    }，
    {
      "@otherwise": "otherwise"
    }
  ]
```

**Comment by lixingwang** [comment]
> How about "@condition/@conditional" which has a verbose generalized syntax, but also support an optional shorthand when using the same variable?
> 
> general:
> 
> ```
>   "myInput": {
>   "@conditional" :[
>     {
>       "$.pathParams.myParam1<foo":"This is param for foo"
>     }，
>     {
>       "$.pathParams.myParam2>foo":"This is param for foo"
>     }，
>     {
>       "$.pathParams.myParam == 200":"200"
>     }，
>     {
>       "@otherwise": "otherwise"
>     }
>   ]
> ```
> 
> shorthand:
> 
> ```
> "myInput": {
>   "@conditional($.pathParams.myParam)" :[
>     {
>       "<foo":"This is param for foo"
>     }，
>     {
>       ">foo":"This is param for foo"
>     }，
>     {
>       "==200":"200"
>     }，
>     {
>       "@otherwise": "otherwise"
>     }
>   ]
> ```

This looks good to me.  @mellistibco please share your thoughts. thx

**Comment by mellistibco** [comment]
looks good to me, seems like the best option...

**Review by fm-tibco — APPROVED** [review]

**Review by mellistibco — APPROVED** [review]

**Pull request merged**
