### PR TITLE
return original array if no child mapping for array mapping

### PR DESCRIPTION
**Pull request by lixingwang**
**What kind of change does this PR introduce?** (check one with "x")
```
[*] Bugfix
[] Feature
[] Code style update (formatting, local variables)
[] Refactoring (no functional changes, no api changes)
[] Other... Please describe:
```

**Fixes**: #

**What is the current behavior?**

**What is the new behavior?**
If there is no child mapping for array mapping then we return original data. such as:
```
     "array": {
                  "@foreach($activity[rest].data.array)":{}
         }
```

We will copy `$activity[rest].data.array` to `array`.  This is the behavior we did in flogo-lib,  so make these changes to keep consistency with previous.

### CODE REVIEW

**Comment by fm-tibco** [comment]
I read this as creating an empty array the length of $activity[rest].data.array.  If I were to assign an array I would do =$activity[rest].data.array .  @mellistibco thoughts on this?

or 

maybe something like this... not sure...

  "array": {
                  "@foreach($activity[rest].data.array)":[ 
                       "=$loop"
                  ]
         }

**Comment by lixingwang** [comment]
@fm-tibco @mellistibco Actually there is possible 2 behavior
1. Do nothing
2. Just create an empty array
3. Copy all from the source array 

I think both 1 and 3 make sense.  I don't think there is much use case to create an empty array.  

There is no mapping at child level we can take is as 3 to copy all from the original. They can remove foreach node if they want to do nothing.

**Comment by fm-tibco** [comment]
Whatever we decide, we should definitely add documentation on the object mapping stuff.  
```    
"array": {
    "@foreach($activity[rest].data.array)":{}
 }
```
It still isn't clear enough to me that the statement above is the same as this
 ```
"array":"=$activity[rest].data.array"
```
I have a question, how do we do the following

array[0] =  $activity[rest].data.array[0].subVal
array[1] =  $activity[rest].data.array[1].subVal
array[2] =  $activity[rest].data.array[2].subVal
array[3] =  $activity[rest].data.array[3].subVal

I think if we resolve this, it will might tell us what is the right approach on this issue.

@mellistibco ?

**Comment by lixingwang** [comment]
@fm-tibco Yes, It is same with `"array":"=$activity[rest].data.array"`.

But we cannot handle this today, the key of must be an real key.
array[0] = $activity[rest].data.array[0].subVal
array[1] = $activity[rest].data.array[1].subVal
array[2] = $activity[rest].data.array[2].subVal
array[3] = $activity[rest].data.array[3].subVal

**Comment by fm-tibco** [comment]
maybe we can do the following with a special "=" value:

copy values:
```
"array": {
    "@foreach($activity[rest].data.array)":{
        "=" : "=$loop"
    }
 }
```

copy sub values:
```
"array": {
    "@foreach($activity[rest].data.array)":{
        "=" : "=$loop.subVal"
    }
 }
```

set fixed values, same length of array:
```
"array": {
    "@foreach($activity[rest].data.array)":{
        "=" : "defaultValue"
    }
 }
```

**Comment by fm-tibco** [comment]
@mellistibco thoughts on this?

**Comment by mellistibco** [comment]
Hmm, tricky. I'm not super fond of any option nor do I have a better suggestion... I think we should probably go with the following. It seems to be the most logical to me...

`
"array": {
    "@foreach($activity[rest].data.array)":{
        "=" : "=$loop.subVal"
    }
 }
`

**Comment by lixingwang** [comment]
thanks, @mellistibco  and @fm-tibco , I will update the PR.

**Pull request merged**
