### PR TITLE
Property cleanup

### PR DESCRIPTION
**Pull request by fm-tibco**
**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[] Feature
[] Code style update (formatting, local variables)
[] Refactoring (no functional changes, no api changes)
[x] Other... Please describe:
```

**Fixes**: 

Fix code to remove extra hop to deprecated method. Update property documentation.

### CODE REVIEW

**Comment by skothari-tibco** [comment]
I think we also need to add `_ "github.com/project-flogo/core/app/propertyresolver"` to the main.go of the engine, right ? I tested the without it and I got the error `Failed to create engine: Unsupported property resolver type - env. Resolver not registered.` But adding the above import to main.go works.

**Comment by fm-tibco** [comment]
The question is should we load the built-in ones by default or have them add that import to the engine.json?  If we think it will always be used then we should definitely add the import, if not .. I'm not sure...  @mellistibco any thoughts?

**Comment by skothari-tibco** [comment]
I'm inclined towards loading it by default. Since we are providing those as  built-in, I think it's fair to have them without having to explicitly add that in engine.json/flogo.json .

**Comment by lixingwang** [comment]
I think it makes sense to have it build-in, either adding in main.go or import.go or elsewhere that we can import automatically.

**Pull request merged**
